version: 2

models:
  - name: stg_procurement 
    description: "Limpeza inicial dos dados de compras."
    columns:
      - name: po_id
        description: "Chave primária da ordem de compra."
        tests:
          - not_null
          - unique